#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2014-11-29 01:02:47 +0000 (Sat, 29 Nov 2014)
#
#  https://github.com/harisekhon/pytools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#  to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

language: python
python:
#  - "2.6"
  - "2.7"
# MySQL in lib doesn't build from pip in Python 3
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  python-krbV fails to compile on PyPy
#  - "pypy"
#  - "pypy3"

sudo: required

env:
#  - DEBUG=1
  - PYTHONUNBUFFERED=1

notifications:
  email: false

branches:
  only:
    - master

cache: pip

services:
  - docker

install:
  - make
  #- pip install --upgrade ndg-httpsclient
  - pip uninstall -y certifi && pip install certifi==2015.04.28

script:
  - make test

after_success:
  - coveralls
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/pytools/trigger/0e69c39f-ea1b-43c7-a97d-cef1252f1400/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/alpine-github/trigger/8d9cb826-48df-439c-8c20-1975713064fc/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/centos-github/trigger/316d1158-7ffb-49a4-a7bd-8e5456ba2d15/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/ubuntu-github/trigger/abd4dbf0-14bc-454f-9cde-081ec014bc48/
  - curl --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/debian-github/trigger/0cfb3fe7-2028-494b-a43b-068435e6a2b3/
